services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: library
      MYSQL_USER: app
      MYSQL_PASSWORD: apppass
    volumes:
      #- ./mysql_data:/var/lib/mysql
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD" ]
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/library?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: app
      SPRING_DATASOURCE_PASSWORD: apppass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      JWT_SECRET: mysecretkeyLongandSecureToUseProjetoMontreal
      CORS_ALLOWED_ORIGINS: http://localhost:4200
    depends_on:
      db:
        condition: service_healthy
  frontend:
    build: ./frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
volumes:
  db_data:
