spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/library?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC}
    username: ${SPRING_DATASOURCE_USERNAME:app}
    password: ${SPRING_DATASOURCE_PASSWORD:apppass}
    hikari:
      connection-timeout: 30000
      initialization-fail-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
  info:
    title: Library API
    version: 1.0
    description: API para gerenciamento de biblioteca


jwt:
  secret: ${JWT_SECRET:mysecretkeyLongandSecureToUseProjetoMontreal}
  expiration-ms: 3600000

server:
  port: 8080

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:4200}
